name: classifier_environment

channels:
  - anaconda
  - conda-forge

dependencies:
  - python=3.9.13
  - pandas=1.4.3
  - shap=0.41.0
  - xgboost=1.6.2
  - matplotlib=3.5.2
  - scikit-learn=1.1.1
  - numpy=1.21.5
  - pip=22.2.2
  - boto3=1.24.28
  - pip:
    - argparse==1.1